export const Skills = [
    {
        name:'C++',
        icon:'../../../assets/c++.png'
    },
    {
        name:'Python',
        icon:'../../../assets/python.png'
    },
    {
        name:'CSS',
        icon:'../../../assets/css.jpg'
    },
    {
        name:'Angular',
        icon:'../../../assets/angular.png'
    },
    {
        name:'GIT',
        icon:'../../../assets/git.png'
    },
    {
        name:'Nodejs',
        icon:'../../../assets/nodejs.png'
    },
    {
        name:'Expressjs',
        icon:'../../../assets/express.png'
    },
    {
        name:'SQL',
        icon:'../../../assets/sql.jpg'
    },
    {
        name:'Javascript',
        icon:'../../../assets/js.png'
    },
    {
        name:'HTML',
        icon:'../../../assets/html.png'
    }
]